Add error handling and messages to prevent running develop
reactioncommerce/cli pull request #148
Opened 2022-10-18 13:40 UTC by breakerbar

Add error handling and messages to prevent running develop while in a directory without a project already defined

solves https://github.com/reactioncommerce/cli/issues/23

Signed-off-by: Matthew Palombi <matt@breakerbar.com>

2022-10-20 01:14 UTC, zenweasel requested changes
@breakerbar When I test this running it in a directory with a package.json I get the error:
```
reaction-cli: Error while parsing package.json
reaction-cli: No project type found

```

I also get it in a valid project

2022-10-20 01:21 UTC, brent-hoover commented
@breakerbar You will also want to fix up your commit message

2022-10-20 12:45 UTC, breakerbar commented
Taking a look - I think I know what it could be.  I'm assuming that when you run `develop api|admin|storefront` you're in a directory that is *only* one of those `projectType` and it must match the one in the command, is that correct?

2022-10-20 14:00 UTC, breakerbar commented
@zenweasel What is the exact command you're running and what is `projectType` set to in the package.json in your current directory for the invalid/valid examples?

2022-10-20 14:19 UTC, zenweasel commented
I get the same error regardless of where I run it from. Seems like it's having a problem parsing the package.json for some reason. I'm running reaction develop in every case

2022-10-20 14:24 UTC, breakerbar commented
Thanks - I can duplicate it on my side, working on it now.

2022-10-31 03:42 UTC, zenweasel commented
@breakerbar Just pinging you that Hacktober is almost over if you want to get this in

2022-10-31 15:09 UTC, breakerbar commented
thanks - I plan to get to it, but it might be later this week.

2024-02-23 18:54 UTC, closed without merging