feature: update command for api project
reactioncommerce/cli pull request #89
Opened 2022-07-11 01:50 UTC by vanpho93

Resolves: https://github.com/reactioncommerce/cli/issues/85

# Solution
Read local package.json and reaction package.sjon on trunk branch,
Compare and update packages
Run npm install

# Testing
inside cli run `npm install -g`
then inside you cli project run `reaction update`

2022-07-11 07:27 UTC, zenweasel reviewed
Looks great! Just a couple of nitpicky questions

2022-07-11 07:27 UTC, zenweasel commented on .eslintrc
> +      "allowTemplateLiterals": true
Why are we making this change? Generally we should never touch this

2022-07-11 07:27 UTC, zenweasel commented on tests/utils/execute.js
> +    if (agnoreError === false) {
Is this maybe supposed to be `ignoreError` rather than `agnoreError`

2022-07-11 07:30 UTC, vanpho93 commented on .eslintrc
> +      "allowTemplateLiterals": true
I used allowTemplateLiterals in here `const invalidPackageJson = `{ "name": "test }`;`
And eslint not allow that.

2022-07-11 07:32 UTC, vanpho93 commented on tests/utils/execute.js
> +    if (agnoreError === false) {
I fixed.

2022-07-11 07:32 UTC, vanpho93 commented on .eslintrc
> +      "allowTemplateLiterals": true
Do you think we should revert this change?

2022-07-11 07:38 UTC, zenweasel commented on .eslintrc
> +      "allowTemplateLiterals": true
Yes, when you encounter a discrepancy between linting and your code the path is to correct your code, not the lint rules. The lint rules are the same for the entire organization.

2022-07-11 07:42 UTC, vanpho93 commented on .eslintrc
> +      "allowTemplateLiterals": true
Understood. I reverted.

2022-07-11 07:49 UTC, brent-hoover approved these changes

2022-07-12 03:04 UTC, zenweasel commented
@tedraykov Second call for PR review

2022-07-12 08:44 UTC, tedraykov requested changes
Overall great job. I added a few comments about typos only. Apart from them, it's good to go.

2022-07-12 08:44 UTC, tedraykov commented on commands/update.js
> +import compareVerions from "compare-versions";
It's a typo
```suggestion
import compareVersions from "compare-versions";
```

2022-07-12 08:44 UTC, tedraykov commented on commands/update.js
> +      outdated: compareVerions.compare(cleanVersion(remoteDependencies[name]), cleanVersion(version), ">")
Rename the default import name here as well.

2022-07-12 08:44 UTC, tedraykov commented on commands/update.js
> +      message: "Do want to update your outdate plugins?",
Outdate is a verb, so `outdated` is the correct spelling here.
```suggestion
      message: "Do want to update your outdated plugins?",
```

2022-07-12 09:08 UTC, tedraykov approved these changes

2022-07-12 23:11 UTC, merged